-- Sprint 18.2 -- Production warehouse bootstrap, Phase 8, step 4 of 8.
--
-- The 9 mart.* tables in the minimum launch contract: current-point market
-- snapshots, 2021 Census demographic profiles, market time series, and
-- rental quarterlies -- read directly by 5 of the 8 granted research
-- functions and 6 of the 10 granted views. All foreign keys reference
-- core.dim_geography (migration 049) and meta.jurisdiction (migration
-- 050), both already created earlier in this bootstrap sequence.
--
-- Column sets, constraints, and indexes extracted byte-accurate from
-- warehouse-validation's final, consolidated shape -- not replayed from
-- the incremental 003->034 add-column history that originally built these
-- tables up over ~15 separate migrations.

create table if not exists mart.suburb_market_snapshot (
  "snapshot_id" uuid default gen_random_uuid() not null,
  "geography_id" text,
  "geography_name" text,
  "state_code" text,
  "reference_month" date,
  "dwelling_type" text,
  "median_sale_price" numeric,
  "sales_volume" integer,
  "median_rent" numeric,
  "gross_yield" numeric,
  "population_growth_1y" numeric,
  "dwelling_approvals_12m" integer,
  "data_coverage_score" numeric,
  "confidence_label" text,
  "source_summary" jsonb,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "latest_sales_period" date,
  "latest_rent_period" date,
  "latest_yield_period" date,
  "latest_approvals_period" date,
  "latest_demographics_period" integer,
  "snapshot_generated_at" timestamp with time zone,
  "coverage_status" text,
  "sales_volume_12m" integer,
  "median_sale_price_12m" numeric,
  "median_sale_price_prev_12m" numeric,
  "annual_price_change_pct" numeric,
  "median_sale_price_detached" numeric,
  "median_sale_price_apartment" numeric,
  "median_sale_price_townhouse" numeric,
  "sales_sample_confidence" text,
  "median_weekly_rent_latest" numeric,
  "median_weekly_rent_prev" numeric,
  "annual_rent_change_pct" numeric,
  "rent_confidence" text,
  "gross_yield_pct" numeric,
  "yield_confidence" text,
  "yield_sale_period_used" date,
  "yield_rent_period_used" date,
  "dwelling_stock_total" integer,
  "approvals_12m" integer,
  "approvals_per_1000_dwellings" numeric,
  "approvals_detached_12m" integer,
  "approvals_other_residential_12m" integer,
  "supply_confidence" text,
  "sales_turnover_pct" numeric,
  "renter_household_pct" numeric,
  "owner_occupier_pct" numeric,
  "total_population" integer,
  "population_growth_2016_2021_pct" numeric,
  "total_households" integer,
  "median_weekly_household_income" integer,
  "renter_share" numeric,
  "owner_with_mortgage_share" numeric,
  "price_to_income_ratio" numeric,
  "rent_to_income_ratio" numeric,
  "est_monthly_repayment_owner_occupier" numeric,
  "est_monthly_repayment_investor" numeric,
  "repayment_to_income_pct" numeric,
  "rba_rate_used" numeric,
  "rba_rate_period" date,
  "assumption_scenario_code" text,
  "affordability_confidence" text,
  "data_quality_status" text,
  "direct_or_derived" text,
  "source_periods" jsonb,
  "metric_provenance" jsonb,
  "missing_metric_reasons" jsonb,
  "geography_code" text,
  "jurisdiction" text,
  "geography_method" text,
  constraint suburb_market_snapshot_pkey primary key (snapshot_id),
  constraint suburb_market_snapshot_geography_id_fkey foreign key (geography_id) references core.dim_geography (geography_id),
  constraint suburb_market_snapshot_jurisdiction_fkey foreign key (jurisdiction) references meta.jurisdiction (jurisdiction_code)
);
create index if not exists suburb_snapshot_compare_idx on mart.suburb_market_snapshot using btree (jurisdiction, coverage_status);
create index if not exists suburb_snapshot_geo_month_idx on mart.suburb_market_snapshot using btree (geography_id, reference_month desc, dwelling_type);
create index if not exists suburb_snapshot_jurisdiction_geocode_idx on mart.suburb_market_snapshot using btree (jurisdiction, geography_code);
create index if not exists suburb_snapshot_state_geoname_idx on mart.suburb_market_snapshot using btree (state_code, geography_name);
create index if not exists suburb_snapshot_state_month_idx on mart.suburb_market_snapshot using btree (state_code, reference_month desc);

create table if not exists mart.postcode_market_snapshot (
  "snapshot_id" uuid default gen_random_uuid() not null,
  "geography_id" text,
  "geography_name" text,
  "state_code" text,
  "reference_month" date,
  "dwelling_type" text,
  "median_sale_price" numeric,
  "sales_volume" integer,
  "median_rent" numeric,
  "gross_yield" numeric,
  "population_growth_1y" numeric,
  "dwelling_approvals_12m" integer,
  "data_coverage_score" numeric,
  "confidence_label" text,
  "source_summary" jsonb,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "latest_sales_period" date,
  "latest_rent_period" date,
  "latest_yield_period" date,
  "latest_approvals_period" date,
  "latest_demographics_period" integer,
  "snapshot_generated_at" timestamp with time zone,
  "coverage_status" text,
  "sales_volume_12m" integer,
  "median_sale_price_12m" numeric,
  "median_sale_price_prev_12m" numeric,
  "annual_price_change_pct" numeric,
  "median_sale_price_detached" numeric,
  "median_sale_price_apartment" numeric,
  "median_sale_price_townhouse" numeric,
  "sales_sample_confidence" text,
  "median_weekly_rent_latest" numeric,
  "median_weekly_rent_prev" numeric,
  "annual_rent_change_pct" numeric,
  "rent_confidence" text,
  "gross_yield_pct" numeric,
  "yield_confidence" text,
  "yield_sale_period_used" date,
  "yield_rent_period_used" date,
  "dwelling_stock_total" integer,
  "approvals_12m" integer,
  "approvals_per_1000_dwellings" numeric,
  "approvals_detached_12m" integer,
  "approvals_other_residential_12m" integer,
  "supply_confidence" text,
  "sales_turnover_pct" numeric,
  "renter_household_pct" numeric,
  "owner_occupier_pct" numeric,
  "total_population" integer,
  "population_growth_2016_2021_pct" numeric,
  "total_households" integer,
  "median_weekly_household_income" integer,
  "renter_share" numeric,
  "owner_with_mortgage_share" numeric,
  "price_to_income_ratio" numeric,
  "rent_to_income_ratio" numeric,
  "est_monthly_repayment_owner_occupier" numeric,
  "est_monthly_repayment_investor" numeric,
  "repayment_to_income_pct" numeric,
  "rba_rate_used" numeric,
  "rba_rate_period" date,
  "assumption_scenario_code" text,
  "affordability_confidence" text,
  "data_quality_status" text,
  "direct_or_derived" text,
  "source_periods" jsonb,
  "metric_provenance" jsonb,
  "missing_metric_reasons" jsonb,
  "geography_code" text,
  "jurisdiction" text,
  "geography_method" text,
  constraint postcode_market_snapshot_pkey primary key (snapshot_id),
  constraint postcode_market_snapshot_geography_id_fkey foreign key (geography_id) references core.dim_geography (geography_id),
  constraint postcode_market_snapshot_jurisdiction_fkey foreign key (jurisdiction) references meta.jurisdiction (jurisdiction_code)
);
create index if not exists postcode_snapshot_compare_idx on mart.postcode_market_snapshot using btree (jurisdiction, coverage_status);
create index if not exists postcode_snapshot_geo_month_idx on mart.postcode_market_snapshot using btree (geography_id, reference_month desc, dwelling_type);
create index if not exists postcode_snapshot_jurisdiction_geocode_idx on mart.postcode_market_snapshot using btree (jurisdiction, geography_code);
create index if not exists postcode_snapshot_state_geoname_idx on mart.postcode_market_snapshot using btree (state_code, geography_name);
create index if not exists postcode_snapshot_state_month_idx on mart.postcode_market_snapshot using btree (state_code, reference_month desc);

create table if not exists mart.suburb_demographic_profile_2021 (
  "profile_id" uuid default gen_random_uuid() not null,
  "geography_id" text,
  "geography_code" text not null,
  "geography_name" text,
  "geography_type" text default 'SAL'::text not null,
  "state_code" text,
  "census_year" integer default 2021 not null,
  "total_population" integer,
  "population_2016" integer,
  "population_2021" integer,
  "population_growth_2016_2021_pct" numeric,
  "median_age" numeric,
  "total_households" integer,
  "family_households" integer,
  "lone_person_households" integer,
  "average_household_size" numeric,
  "median_weekly_household_income" integer,
  "median_weekly_personal_income" integer,
  "median_weekly_family_income" integer,
  "census_median_weekly_rent" integer,
  "census_median_monthly_mortgage" integer,
  "renter_household_pct" numeric,
  "owner_with_mortgage_pct" numeric,
  "owner_outright_pct" numeric,
  "occupied_dwelling_count" integer,
  "unoccupied_dwelling_count" integer,
  "detached_house_pct" numeric,
  "apartment_unit_pct" numeric,
  "geography_method" text default 'direct'::text not null,
  "confidence_label" text not null,
  "data_quality_status" text default 'passed'::text not null,
  "missing_metric_reasons" jsonb,
  "source_summary" jsonb,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "population_growth_method" text,
  "population_growth_confidence" text,
  "population_growth_correspondence_version" text,
  "population_growth_source_dataset_id" text,
  constraint suburb_demographic_profile_2021_pkey primary key (profile_id),
  constraint suburb_demographic_profile_2021_geography_id_fkey foreign key (geography_id) references core.dim_geography (geography_id)
);
create index if not exists suburb_demographic_profile_geo_idx on mart.suburb_demographic_profile_2021 using btree (geography_id);
create index if not exists suburb_demographic_profile_state_idx on mart.suburb_demographic_profile_2021 using btree (state_code);

create table if not exists mart.postcode_demographic_profile_2021 (
  "profile_id" uuid default gen_random_uuid() not null,
  "geography_id" text,
  "geography_code" text not null,
  "geography_name" text,
  "geography_type" text default 'POA'::text not null,
  "state_code" text,
  "census_year" integer default 2021 not null,
  "total_population" integer,
  "population_2016" integer,
  "population_2021" integer,
  "population_growth_2016_2021_pct" numeric,
  "median_age" numeric,
  "total_households" integer,
  "family_households" integer,
  "lone_person_households" integer,
  "average_household_size" numeric,
  "median_weekly_household_income" integer,
  "median_weekly_personal_income" integer,
  "median_weekly_family_income" integer,
  "census_median_weekly_rent" integer,
  "census_median_monthly_mortgage" integer,
  "renter_household_pct" numeric,
  "owner_with_mortgage_pct" numeric,
  "owner_outright_pct" numeric,
  "occupied_dwelling_count" integer,
  "unoccupied_dwelling_count" integer,
  "detached_house_pct" numeric,
  "apartment_unit_pct" numeric,
  "geography_method" text default 'direct'::text not null,
  "confidence_label" text not null,
  "data_quality_status" text default 'passed'::text not null,
  "missing_metric_reasons" jsonb,
  "source_summary" jsonb,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "population_growth_method" text,
  "population_growth_confidence" text,
  "population_growth_correspondence_version" text,
  "population_growth_source_dataset_id" text,
  constraint postcode_demographic_profile_2021_pkey primary key (profile_id),
  constraint postcode_demographic_profile_2021_geography_id_fkey foreign key (geography_id) references core.dim_geography (geography_id)
);
create index if not exists postcode_demographic_profile_geo_idx on mart.postcode_demographic_profile_2021 using btree (geography_id);
create index if not exists postcode_demographic_profile_state_idx on mart.postcode_demographic_profile_2021 using btree (state_code);

create table if not exists mart.suburb_market_timeseries (
  "ts_row_id" uuid default gen_random_uuid() not null,
  "geography_id" text,
  "geography_type" text default 'SAL'::text not null,
  "reference_period" date not null,
  "period_type" text not null,
  "dwelling_type" text,
  "metric_family" text not null,
  "transaction_count" integer,
  "median_sale_price" numeric,
  "median_weekly_rent" numeric,
  "gross_yield_percentage" numeric,
  "approvals_count" integer,
  "rate_percent" numeric,
  "confidence_label" text not null,
  "source_dataset" text,
  "created_at" timestamp with time zone default now() not null,
  "jurisdiction" text,
  "state_code" text,
  "geography_method" text,
  "metric_provenance" jsonb,
  constraint suburb_market_timeseries_pkey primary key (ts_row_id),
  constraint suburb_market_timeseries_geography_id_fkey foreign key (geography_id) references core.dim_geography (geography_id),
  constraint suburb_market_timeseries_jurisdiction_fkey foreign key (jurisdiction) references meta.jurisdiction (jurisdiction_code)
);
create index if not exists suburb_market_timeseries_geo_period_idx on mart.suburb_market_timeseries using btree (geography_id, reference_period desc);
create index if not exists suburb_timeseries_jurisdiction_idx on mart.suburb_market_timeseries using btree (jurisdiction, geography_id, reference_period desc);

create table if not exists mart.postcode_market_timeseries (
  "ts_row_id" uuid default gen_random_uuid() not null,
  "geography_id" text,
  "geography_type" text default 'POA'::text not null,
  "reference_period" date not null,
  "period_type" text not null,
  "dwelling_type" text,
  "metric_family" text not null,
  "transaction_count" integer,
  "median_sale_price" numeric,
  "median_weekly_rent" numeric,
  "gross_yield_percentage" numeric,
  "approvals_count" integer,
  "rate_percent" numeric,
  "confidence_label" text not null,
  "source_dataset" text,
  "created_at" timestamp with time zone default now() not null,
  "jurisdiction" text,
  "state_code" text,
  "geography_method" text,
  "metric_provenance" jsonb,
  constraint postcode_market_timeseries_pkey primary key (ts_row_id),
  constraint postcode_market_timeseries_geography_id_fkey foreign key (geography_id) references core.dim_geography (geography_id),
  constraint postcode_market_timeseries_jurisdiction_fkey foreign key (jurisdiction) references meta.jurisdiction (jurisdiction_code)
);
create index if not exists postcode_market_timeseries_geo_period_idx on mart.postcode_market_timeseries using btree (geography_id, reference_period desc);
create index if not exists postcode_timeseries_jurisdiction_idx on mart.postcode_market_timeseries using btree (jurisdiction, geography_id, reference_period desc);

create table if not exists mart.suburb_rent_quarterly (
  "mart_row_id" uuid default gen_random_uuid() not null,
  "geography_id" text,
  "geography_name" text,
  "state_code" text,
  "reference_quarter" date not null,
  "dwelling_type" text not null,
  "median_weekly_rent" numeric,
  "rental_count" integer,
  "sample_size_confidence" text,
  "confidence_label" text,
  "correspondence_method" text,
  "source_summary" jsonb,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint suburb_rent_quarterly_pkey primary key (mart_row_id),
  constraint suburb_rent_quarterly_geography_id_reference_quarter_dwelli_key unique (geography_id, reference_quarter, dwelling_type),
  constraint suburb_rent_quarterly_geography_id_fkey foreign key (geography_id) references core.dim_geography (geography_id)
);
create index if not exists mart_suburb_rent_geo_period_notnull_idx on mart.suburb_rent_quarterly using btree (geography_id, reference_quarter desc) where (median_weekly_rent is not null);
create index if not exists mart_suburb_rent_state_idx on mart.suburb_rent_quarterly using btree (state_code, reference_quarter desc);

create table if not exists mart.postcode_rent_quarterly (
  "mart_row_id" uuid default gen_random_uuid() not null,
  "geography_id" text,
  "geography_name" text,
  "state_code" text,
  "reference_quarter" date not null,
  "dwelling_type" text not null,
  "median_weekly_rent" numeric,
  "rental_count" integer,
  "sample_size_confidence" text,
  "confidence_label" text,
  "correspondence_method" text,
  "source_summary" jsonb,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint postcode_rent_quarterly_pkey primary key (mart_row_id),
  constraint postcode_rent_quarterly_geography_id_reference_quarter_dwel_key unique (geography_id, reference_quarter, dwelling_type),
  constraint postcode_rent_quarterly_geography_id_fkey foreign key (geography_id) references core.dim_geography (geography_id)
);
create index if not exists mart_postcode_rent_geo_period_notnull_idx on mart.postcode_rent_quarterly using btree (geography_id, reference_quarter desc) where (median_weekly_rent is not null);
create index if not exists mart_postcode_rent_state_idx on mart.postcode_rent_quarterly using btree (state_code, reference_quarter desc);

create table if not exists mart.lga_rent_quarterly (
  "mart_row_id" uuid default gen_random_uuid() not null,
  "geography_id" text,
  "geography_name" text,
  "state_code" text,
  "reference_quarter" date not null,
  "dwelling_type" text not null,
  "median_weekly_rent" numeric,
  "rental_count" integer,
  "sample_size_confidence" text,
  "confidence_label" text,
  "correspondence_method" text,
  "source_summary" jsonb,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint lga_rent_quarterly_pkey primary key (mart_row_id),
  constraint lga_rent_quarterly_geography_id_reference_quarter_dwelling__key unique (geography_id, reference_quarter, dwelling_type),
  constraint lga_rent_quarterly_geography_id_fkey foreign key (geography_id) references core.dim_geography (geography_id)
);
create index if not exists mart_lga_rent_geo_period_notnull_idx on mart.lga_rent_quarterly using btree (geography_id, reference_quarter desc) where (median_weekly_rent is not null);
create index if not exists mart_lga_rent_state_idx on mart.lga_rent_quarterly using btree (state_code, reference_quarter desc);
